### ISSUE TITLE
Add support for the NoSQL for CosmosDB emulator (local)

### ISSUE THREAD

**Issue by cheenamalhotra** [Azure/azure-cosmosdb-ads-extension#103]
_Originally opened in Azure Data Studio: https://github.com/microsoft/azuredatastudio/issues/24925
Author: @ericvdberge_ 

----------------------

I would like to have a possibility to use azure data studio in combination with the NoSQL for CosmosDB emulator (local) testing environment.

The alternative is to use the data explorer on the local website that the emulator is providing, but it would be way nicer to use azure data studio to connect with the databases.

I am running the docker container of the emulator that you can find [here](https://learn.microsoft.com/en-us/azure/cosmos-db/emulator):

**Comment by languy** [comment]
NoSQL support is currently available in the ADS insider track. You can download ADS Insiders [here](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and install the Azure Cosmos DB extension v0.4.0 which supports NoSQL. Connect using the emulator's connection string and you should be able to manage your databases/collections and also query the data via a query editor.
