### ISSUE TITLE
RBAC Support?  Local Authorization is disabled. Use an AAD token to authorize all requests

### ISSUE THREAD

**Issue by spottedmahn** [Azure/azure-cosmosdb-ads-extension#120]
We're using RBAC for our CosmosDB: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/security/how-to-grant-data-plane-role-based-access

When I try to query a container I get:

> Response status code does not indicate success:
Unauthorized (401); Substatus: 0; Activityld: blah; Reason: (Local
Authorization is disabled. Use an AAD token to authorize
all requests. Activityld: blah, Windows/10.O.20348 cosmos-
netstandard-sdk/3.18.0, Windows/10.O.22621 cosmos-
netstandard-sdk/3.30.8);

Does the extension currently support RBAC?  Maybe I need to configure something if it does?

I believe it is this setting in the [Azure Cosmos DB Explorer](https://cosmos.azure.com/?feature.enableAadDataPlane=true):

![Image](https://github.com/user-attachments/assets/5da60bd5-febc-4c40-a10b-f839ec3ef566)

Related: https://learn.microsoft.com/en-us/answers/questions/1161211/cosmos-db-enforcing-rbac-as-the-only-authenticatio

**Comment by markjbrown** [comment]
This is an RBAC issue. This setting in the portal enables Entra Auth but it doesn't do anything about RBAC. You still have to apply RBAC policies to the account/database/container for each of the service principals trying to access it.

I kind of grew annoyed at having to do this every time using hand-written az cli scripts designed to do one account at a time so I wrote one that did it in bulk for every account I own in my subscription and in resource groups for other subscriptions I have admin rights to.

This isn't yet published to the official az cli samples repo (in PR now) but you can grab the script I wrote here from my repo.
https://github.com/markjbrown/azure-cli-samples/blob/master/cosmosdb/common/rbac-bulk-apply.sh

Hope this helps.

PS: If you also have Firewall rules applied in a similar fashion, I also have another az cli script that applies Portal access to them. It will also sniff out your local IP and add that to the IP Firewall policy as well. You can find that script here. 
https://github.com/markjbrown/azure-cli-samples/blob/master/cosmosdb/common/ipfirewall-bulk-add.sh It's worth noting that if you use a VPN to access your Cosmos accounts this script cannot pick up that IP address. In those cases what I would suggest is to hard code the CIDR range for the VPN and add that to the IP addresses array. This way you can get portal access from any VPN session.

Hope that helps.

**Comment by Pilchie** [comment]
@sevoku can confirm, but I'm not sure if RBAC is supported in the ADS extension right now. It is supported in the VSCode extension however: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb

**Comment by spottedmahn** [comment]
>You still have to apply RBAC policies to the account/database/container for each of the service principals trying to access it.

they must be applied already as I'm able to access the containers in the web ui but not from Azure Data Studio. 🤔

**Comment by spottedmahn** [comment]
>It is supported in the VSCode extension however [Azure Databases - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb)

confirmed, I can access from VS Code w/ Azure Databases extension using RBAC!!

**Comment by Pilchie** [comment]
Thanks - I'm going to close this as not planned, as we are focusing investments on the VSCode extension right now.
