### ISSUE TITLE
User with Cosmos DB Account Reader Role is not able to access the account in Azure Data Studio

### ISSUE THREAD

**Issue by yanfang-ma** [Azure/azure-cosmosdb-ads-extension#121]
If the user is granted Cosmos DB Account Reader Role, when trying to access the Cosmos DB account from Azure Data Studio, below error is populated:

{"error":{"code":"AuthorizationFailed","message":"The client 'XXX' with object id 'XXX' does not have authorization to perform action **'Microsoft.DocumentDB/databaseAccounts/listConnectionStrings/action'** over scope '/subscriptions/subid/resourceGroups/rg/providers/Microsoft.DocumentDB/databaseAccounts/accountname' or the scope is invalid. If access was recently granted, please refresh your credentials."}

Based on below code https://github.com/Azure/azure-cosmosdb-ads-extension/blob/4d379ddb101b81d48252655a709b47f5690f379f/src/Services/AbstractBackendService.ts#L39, 
it seems that when authenticationType is MFA, it will call "retrieveConnectionStringFromArm', while Cosmos DB Account Reader Role does not have the listConnectionStrings action.

However, since user is is granted Cosmos DB Account Reader Role, the expected behavior is that user can view data in the Cosmos DB account.

Due to this issue, customer has to create the connection using the Cosmos DB account's read-only connection string.

**Comment by Pilchie** [comment]
See also https://github.com/Azure/azure-cosmosdb-ads-extension/issues/120.  We have added RBAC support to the VSCode extension.  We're currently focusing there instead of here, so I'm going to close this as Not Planned.
