### ISSUE TITLE
SQL API support

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-cosmosdb-ads-extension#36]
The title says it all :wink:

**Comment by languy** [comment]
Addressed in latest [0.1.4 release](https://github.com/microsoft/azuredatastudio/pull/21053).

**Comment by thomaslevesque** [comment]
@languy

Thanks, but it doesn't seem to change anything...
I installed the new VSIX, but I still only have "Microsoft SQL Server" and "Mongo account" in the connection type dropdown.
![image](https://user-images.githubusercontent.com/1864281/199559544-003f673d-e6bb-4b25-8cb3-2702e17271f2.png)
How do I connect to a Cosmos DB account?

**Comment by thomaslevesque** [comment]
I also tried to build a Mongo connection string as described [here](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/connect-account#connection-string-requirements), but it just stays in "Connecting..." state forever.
Anyway, I don't understand why I should have to go through _anything_ related to MongoDB. I don't use the MongoDB API, I always used only the SQL API.

**Comment by languy** [comment]
@thomaslevesque Apologies, I commented the wrong ticket (I deleted my comment). We are working on SQL api support, but the change isn't . Please stay tuned.

**Comment by mdanylyuk** [comment]
Hello guys.
Is there any news about the extension?

**Comment by languy** [comment]
> Hello guys. Is there any news about the extension?
Still working on it and getting closer.

**Comment by mdanylyuk** [comment]
Hello guys,
Is there any news about this extension?

**Comment by languy** [comment]
@mdanylyuk Yes, we have been working on this and completed major milestones. Please stay tuned for another update soon.

**Comment by languy** [comment]
I am pleased to announce that we just released a new version 0.4.0 of the extension with support for Cosmos DB NoSQL.
You have to install Azure Data Studio Insider as it is not, yet available on the main Azure Data Studio release.
For now, you have to enter the connection information manually as the resources do not appear in the connection dialog Azure, yet.

**Comment by languy** [comment]
The insider build will now display the NoSql resources in the connection dialog Azure tree.

**Comment by mdanylyuk** [comment]
Hello guys,
Do we know when the extension will be in GA?
