### ISSUE TITLE
Please fix the infinite loading

### ISSUE THREAD

**Issue by alanrenmsft** [Azure/azure-cosmosdb-ads-extension#37]
**Note**
This is copied from azure data studio repo: https://github.com/microsoft/azuredatastudio/issues/20417. Created by @MortenMeisler

**Description from the original issue:**

When I try to connect via connection string I get an infinite loading.

![image](https://user-images.githubusercontent.com/17620242/185575544-79e117fd-f06f-4ab2-85e0-6ee2567c8da0.png)

Nomatter what might be causing this, it's very bad practice with no feedback here.

Using latest version: 1.38.0

I'm connecting via Mongo account, using Azure Cosmos DB API extension.
Running on Windows Server 2012.

**Comment by alanrenmsft** [comment]
@languy  FYI

**Comment by languy** [comment]
@MortenMeisler We have fixed some connection bugs with connection in the latest version. Can you confirm whether it works now? (note that currently there is no way to set the timeout. We're using the mongo client to connect, but the timeout option (if it exists) isn't exposed).
