### ISSUE TITLE
Connection Failure to Mongo account

### ISSUE THREAD

**Issue by cheenamalhotra** [Azure/azure-cosmosdb-ads-extension#85]
_Originally reported: https://github.com/microsoft/azuredatastudio/issues/23146#issue-1711726280_

By @sailorjack
Issue Type: <b>Bug</b>

I tried to connect my Azure Cosmos DB (Mongo DB) following the instructions in https://learn.microsoft.com/de-de/sql/azure-data-studio/quickstart-azure-cosmos-db-mongodb?view=sql-server-ver16.
I got an connection error with the following message:
"Failed to connect: getaddrinfo ENOTFOUND eta-db-2.mongo.cosmos.azure.com"
Same issue occurred while using the connection string instead.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.1.2
azcli|Mic|1.8.0
azure-cosmosdb-ads-extension|Mic|0.3.3
azuredatastudio-oracle|Mic|0.1.2
dsct-oracle-to-ms-sql|Mic|0.4.1
net-6-runtime|Mic|1.1.0
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.0.1
mongodb-vscode|mon|0.9.3

</details>

-------------------
Moving issue here as it applies to Mongo DB extension.

**Comment by sailorjack** [comment]
pinging the DB is not working due to host resolution behind our companies proxy. I can pass the proxy on higher OSI layers, but since ping is operating on quite low levels it is not working.

**Comment by languy** [comment]
I am able to ping it and resolve the DNS address, so your account is most likely up and running.
The original error seems to indicate that the mongo client isn't able to resolve the hostname.

Are you able to perform `nslookup eta-db-2.mongo.cosmos.azure.com`?

**Comment by languy** [comment]
Closing stale issue. If the issue remains, please contact support through the Azure portal in your resource page.
