### ISSUE TITLE
Mongo Shell extension repeatedly dowloads installer 

### ISSUE THREAD

**Issue by DavideDelVecchio** [Azure/azure-cosmosdb-ads-extension#87]
Type: Bug

I've updated to the newest version of ADS . I just connected to a Mongo cluster by using the provided Mongo settings window . When I click on Open Mongo Shell the download process is looping, repeatedly Downloading the MongoShell see the log (truncated)

Installing MongoShell to .azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Done installing MongoShell

Installing MongoShell to .azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Done installing MongoShell
Installing MongoShell to .azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.3.3\local-resources\v0.3.0\mongoshell\Windows
Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Downloading https://github.com/Azure/azure-cosmosdb-ads-extension/releases/download/v0.3.0/mongoshell-1.6.0-win32-x64.zip
(34,679 KB)Done installing MongoShell

Azure Data Studio version: azuredatastudio 1.44.1 (https://github.com/microsoft/azuredatastudio/commit/8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

System Info
Item	Value
CPUs	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)
GPU Status	2d_canvas: enabled
canvas_oop_rasterization: disabled_off
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
skia_renderer: enabled_on
video_decode: enabled
video_encode: enabled
vulkan: disabled_off
webgl: enabled
webgl2: enabled
webgpu: disabled_off
Load (avg)	undefined
Memory (System)	31.60GB (13.75GB free)
Process Argv	
Screen Reader	no
VM	0%
Extensions (15)
Extension	Author (truncated)	Version
admin-pack	Mic	0.0.2
agent	Mic	0.49.0
arc	Mic	1.8.0
azcli	Mic	1.8.0
azure-cosmosdb-ads-extension	Mic	0.3.3
azuredatastudio-dma-oracle	Mic	4.1.2
azuredatastudio-oracle	Mic	0.1.3
azuredatastudio-postgresql	Mic	0.3.1
dacpac	Mic	1.13.0
import	Mic	1.5.5
net-6-runtime	Mic	1.1.0
profiler	Mic	0.12.2
schema-compare	Mic	1.19.0
sql-assessment	Mic	0.6.4
sql-database-projects	Mic	1.1.1

**Comment by DavideDelVecchio** [comment]
Hi @languy This log was produced in the  command output from VS Code, just as soon as I click the "Open Mongo Shell" botton. I've only clicked it once ,so there's no possibility that I've incurred in multi execution. I've only removed the full path from the log. It continues forevever and it effectively donwloads the installer and decompres it,  proceeding with the installation. When the command outpout is closed no more lines are generated. I will try with the new version and I agree it can be a permission issue . Have you tested it on Windows_NT x64 10.0.22621 ? Thanks

**Comment by languy** [comment]
On the logs: you can open the developer console log and see if there is any error (in red). Hit Ctrl-Shift-P and type "Toggle developer tools". Then click on the "Console" tab.
Yes, I have tested on the same version Windows build (10.0.22621) and ADS version as well (1.44.1).
