### ISSUE TITLE
the connection string for Cosmos Account NoSQL  expects a mongo string

### ISSUE THREAD

**Issue by DavideDelVecchio** [Azure/azure-cosmosdb-ads-extension#89]
Type: <b>Bug</b>

I was creating a connection with a NoSQL Cosmos DB Account (no Mongo API) with the connection wizard . After selecting the connection string mode,  fails expecting a Mongo Connection string 
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
	at new ConnectionString 

Extension version: 0.3.4
Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (14.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by languy** [comment]
Correct, the current version does not support NoSQL, yet. We are working on adding NoSQL support.
